name: LegendaryAllies
main: com.ne0nx3r0.legendaryallies.LegendaryAlliesPlugin
version: '0.9a'
description: Addon for EchoPet that allows players to get powerful summons
commands:
    la:
      description: Legendary ally commands
permissions:
  legendaryallies.tester:
    description: Is legendary allies tester
    default: false
  legendaryallies.admin:
    description: Is legendary allies admin
    default: false
softdepend: [Essentials]